---
abstract: 'It is a tool that confirms the command result to various hosts connected with ssh. '
author:
  - 'kazuhiko yamakura <yamakura@cpan.org>'
build_requires:
  File::Spec: 0
  IO::All: 0
  IPC::Shareable: 0
  Parallel::ForkManager: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Yoyo
no_index:
  directory:
    - inc
    - t
requires:
  Filter::Util::Call: 0
version: 0.00001
